version: '3.9'
services:
  redis:
    container_name: redis_container
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes:
      - ./docker-volumes/cache:/data
mongodb:
  container_name: mongodb_container
  image: mongo:latest
  restart: always
  ports:
    - '27017:27017'
  volumes:
    - ./docker-volumes/data:/data/db
mysql:
  container_name: mysql_container
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_PASSWORD={MYSQL_PASSWORD}
  ports:
    - '3306:3306'
  volumes:
    - ./docker-volumes/mysql:/var/lib/mysql
postgres:
  container_name: postgres_container
  image: postgres
  restart: always
  environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  ports:
    - '5432:5432'
  volumes:
    - ./docker-volumes/postgres:var/lib/postgresql
rabbitmq:
  container_name: rabbitmq_container
  image: rabbitmq:3.13-rc-management-alpine
  restart: always
  ports:
    #AMQP port
    - '5672:5672'
    #Management port
    - '15672:15672'
  environment:
